apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Create namespace for crowsnest
  - crowsnest-namespace.yaml
  # Amend kubelet.conf using MachineConfig
  - crowsnest-kubeletconfig.yaml

  # Add MachineConfig for Static Pod 
  - crowsnest-mco.yaml

